'use client';

import { Inter } from "next/font/google";
import { ThemeProvider } from '@mui/material/styles';
import theme from './theme';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Pantry Tracker",
//   description: "Generated by create next app",
// };


export default function RootLayout({ children }) {
  return (
    <ThemeProvider theme={theme}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ThemeProvider>
    
  );
}